version: '3'
services:
  ostis:
    build: ./ostis
    container_name: ostis
    volumes:
      - ./ostis:/ostis
    restart: on-failure
    network_mode: host
    command: sh ostis --build_kb --sctp

  flask:
    build: ./src
    container_name: web-cs-application
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: always
    volumes:
      - ./web-cs-application:/web-cs-application
#    links:
#      - ostis
    network_mode: host
    command: python __main__.py

  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - flask
    ports:
      - "127.0.0.1:7050:7050"
