version: '3'
services:
  ostis:
    build: ./dockerized-ostis
    container_name: ostis
    volumes:
      - ./dockerized-ostis:/dockerized-ostis
    restart: on-failure
    network_mode: host
    command: sh ostis --all

  rest-server:
    build: ./src
    container_name: rest-server
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: always
    volumes:
      - ./web-cs-application/src/:/web-cs-application/src/
#    links:
#      - ostis
    network_mode: host
    command: python3 -m py-scripts.rest.__main__

  web-server:
    build: ./src
    container_name: web-server
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: always
    volumes:
      - ./web-cs-application/src/:/web-cs-application/src/
#    links:
#      - rest-server
    network_mode: host
    command: python3 -m py-scripts.web.__main__

  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - rest-server
      - web-server
